# Generated by Django 3.2.4 on 2021-07-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('post', models.TextField(max_length=100000000)),
                ('dat', models.DateTimeField(auto_now_add=True)),
                ('upd', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
